# Generated by Django 4.1.5 on 2023-01-22 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('HateMate_Backend_App', '0001_initial'), ]

    operations = [migrations.RunSQL(
        "INSERT INTO \"HateMate_Backend_App_classification\" (id, classification) VALUES (7, 'harmful slander'),	(3, 'violence & killing'), (1, 'negative stereotyping'), (0, 'no hate'), (4, 'equation'), (5, 'normalization of existing discrimination'), (2, 'dehumanization'), (6, 'disguise as irony') ON CONFLICT (id) DO UPDATE SET classification = EXCLUDED.classification;")]
